/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jl_pjdemo_PjJni */

#ifndef _Included_com_jl_pjdemo_PjJni
#define _Included_com_jl_pjdemo_PjJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jl_pjdemo_PjJni
 * Method:    init
 * Signature: (Lcom/jl/pjdemo/PjCb;)I
 */
JNIEXPORT jint JNICALL Java_com_jl_pjdemo_PjJni_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jl_pjdemo_PjJni
 * Method:    uninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jl_pjdemo_PjJni_uninit
  (JNIEnv *, jobject);

/*
 * Class:     com_jl_pjdemo_PjJni
 * Method:    start
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jl_pjdemo_PjJni_start
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jl_pjdemo_PjJni
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jl_pjdemo_PjJni_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_jl_pjdemo_PjJni
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jl_pjdemo_PjJni_version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
